### ISSUE TITLE
Multiple data arguments

### ISSUE THREAD

**Issue by trdavidson** [szymonmaszke/torchlambda#12]
Hi @szymonmaszke - this project is awesome. Went through the `resnet` example setup and works as advertised. Currently the `yaml` template is setup for a single `data` field, that holds one tensor. As I'm not too familiar with c++, could you perhaps give some guidance on how one would send multiple data fields? e.g. `data1, data2, etc.`!

Thanks!

**Comment by szymonmaszke** [comment]
Currently that would need rewriting example `.cpp` code which you can generate with `torchlambda template` (see [documentation](https://github.com/szymonmaszke/torchlambda/wiki/Commands#torchlambda-template)).

If your `data1, data2, ..., dataN` are all tensors of the same (or similar shape) the easiest way to proceed without going into C++ would be:

- stack all of those into `N` dimensional tensor
- make your model take single input and "unpack" into specific tensors inside it
- same for output if there is more than one 

Otherwise it really depends what is going on with what you want to deploy so I'd need more detail.

**Comment by trdavidson** [comment]
apologies for not getting back earlier, thanks for your response! I ended up implementing both, and ultimately opted for slightly rewriting the tensor packing logic to stay with the clean template as suggested.
